Modified tag feature (emergency and close friend)
AY2324S1-CS2103T-T17-4/tp pull request #94
Opened 2023-10-16 17:07 UTC by tanteckfang

I have edited the tag feature such that it can only accept 2 emergency tag, and it will automatically convert it to 'EMERGENCY'. I also improve the feature such that if someone type 't/ cf' it will add a 'Close Friend' tag to the contact

2023-10-16 19:28 UTC, Carlintyj reviewed
Hello! Next time please continue to branch off the master instead of a branch of another PR. 

I like how you made a "cf" shortcut and capitalise "EMERGENCY" when adding of the tag. Also you limited the number of emergency contacts good job!

2023-10-16 19:35 UTC, leontan2 requested changes
Hi Teck Fang, nice progress with the code!
 
However, upon review, I've noticed that the code does not fully meet the specified requirements in terms of tag command.
It seems that tags allowed by the user are not addressed as expected.

Would it be better for the user to only be able to tag their Friends, Close Friends and Emergency, perhaps using an ENUM class would be more appropriate since there are only 3 categories for the people that are added to the addressbook.

 Also, remember to assign yourself as the assignee and assign the development to the issue for the PR tracker!

2023-10-17 09:04 UTC, tanteckfang commented
Hi Leon and Carlin, thanks for your suggestion, tryuly appreciate it. I have made some changes such that it can only allow three types of tags which are Friends, Close Friends and EMERGENCY

2023-10-17 09:20 UTC, Carlintyj commented on src/main/java/seedu/address/logic/commands/AddCommand.java
Hi TF, are you able to change line 39 and 40?

2023-10-17 09:23 UTC, Carlintyj commented on src/main/java/seedu/address/model/tag/Tag.java
> +            "Only three kind of tag names are allowed: Friends, Close Friends (or cf), and EMERGENCY'";
Is it "Friends" and "Close Friends" or "Friend" and "Close Friend"

2023-10-17 09:46 UTC, joel-foo commented
Hi, thanks for helping to make the changes. however, something minor, I'm not sure we should use "EMERGENCY" instead of "Emergency". I think standardising the tags to be the same case format looks better on the UI. What do you guys think?

2023-10-17 10:14 UTC, joel-foo commented
LGTM! If you have time in the future, you can trying creating an Enum class, as Leon mentioned. Will merge this now.

2023-10-17 10:14 UTC, joel-foo approved these changes
LGTM!

2023-10-17 10:16 UTC, joel-foo commented
> Hi Teck Fang, nice progress with the code!
> 
> However, upon review, I've noticed that the code does not fully meet the specified requirements in terms of tag command. It seems that tags allowed by the user are not addressed as expected.
> 
> Would it be better for the user to only be able to tag their Friends, Close Friends and Emergency, perhaps using an ENUM class would be more appropriate since there are only 3 categories for the people that are added to the addressbook.
> 
> Also, remember to assign yourself as the assignee and assign the development to the issue for the PR tracker!

@leontan2, could you help remove your "request changes" so I can merge this? Thanks.

2023-10-17 12:43 UTC, leontan2 approved these changes
I have seen the changes made to the PR, thanks for making those changes
LGTM!

2023-10-17 13:36 UTC, merged